import {it,expect} from 'vitest';
import {confidenceGrade} from './confidence';
it.each([['Cut off part of his left ea','Cut off part of his left ear'],['mitocondria','mitochondria'],['photosythesis','photosynthesis']])('forgives harmless typo %s',(a,b)=>expect(confidenceGrade(a,b).result).toBe('strong_correct'));
it.each([['right ear','left ear'],['velocity decreases','velocity increases'],['does not contain','does contain'],['after 1900','before 1900'],['Germany invaded France','France invaded Germany'],['1946','1945'],['6','5']])('protects factual change %s',(a,b)=>expect(confidenceGrade(a,b).result).toBe('incorrect'));
it.each([['50%','0.5'],['1/2','0.5'],['2.0','2'],['x²','x^2']])('recognizes safe math equivalence %s',(a,b)=>expect(confidenceGrade(a,b).result).toBe('strong_correct'));
it.each([['buy','purchase'],['big','large'],['mitochondria generates energy','mitochondria produces energy']])('uses same-synset evidence %s',(a,b)=>{const grade=confidenceGrade(a,b);expect(grade.signals?.synonymMatches?.length).toBeGreaterThan(0);expect(grade.accuracy).toBeGreaterThanOrEqual(.7);});
it('does not conflate categories or alternate senses without context',()=>{expect(confidenceGrade('animal','dog').accuracy).toBeLessThan(.7);expect(confidenceGrade('river','bank').accuracy).toBeLessThan(.7);});
it.each([true,false])('respects accents independently of strict=%s',strict=>{expect(confidenceGrade('arbol','árbol',strict,false).result).toBe('incorrect');expect(confidenceGrade('arbol','árbol',strict,true).result).toBe('strong_correct');});
it('is deterministic, bounded, and caches repeated lexical evidence',()=>{const first=confidenceGrade('mitochondria generates energy','mitochondria produces energy');const start=performance.now();for(let i=0;i<1000;i++)expect(confidenceGrade('mitochondria generates energy','mitochondria produces energy')).toEqual(first);expect(performance.now()-start).toBeLessThan(1500);expect(confidenceGrade('a'.repeat(10000),'b'.repeat(10000)).accuracy).toBe(0);});
